### ISSUE TITLE
connect secure feature

### ISSUE THREAD

**Issue by almeida-samuel** [tadasr/react-native-iot-wifi#1]
Hello @tadasr how's going?

Are you going to implement the connect secure any time soon? If not, do you have a lib that works both iOS and android?

Thanks

**Comment by tadasr** [comment]
Hi, @almeida-samuel. I was on vocation for a month. Had no plan to implement connect secure any time soon... I can add implementation, but have no time to test it properly on devices.

**Comment by pstanton** [comment]
would be great to get something implemented - i'm sure its dead easy. this library is fairly useless without it.

**Comment by jwktje** [comment]
@pstanton I'd say submit a PR 👍

**Comment by tadasr** [comment]
@almeida-samuel `connectSecure()` should work on [v0.3.0](https://github.com/tadasr/react-native-iot-wifi/tree/0.3.0), see [example](https://github.com/tadasr/react-native-iot-wifi/blob/master/example/App.js#L58) for implementation.
