### ISSUE TITLE
Improve documentation on how to install this library

### ISSUE THREAD

**Issue by thehellmaker** [tadasr/react-native-iot-wifi#19]
I got referred to this library from here https://github.com/blackdeve/react-native-wifi/issues/25

The readme doesn't include how to install this library initially for android. Is it the same as any other react-native libraries work?

npm install react-native-iot-wifi --save
react-native link react-native-iot-wifi

And does this installation have to be done before doing the installation steps for ios in the readme of this library?

I can commit the documentation myself to this library.

**Comment by mmahdigh** [comment]
If you're using RN versions >= 0.60 (since they have Autolinking capability) then you only need to do `npm install --save react-native-iot-wifi` but in prior versions I guess you need to do the linking manually via `react-native link react-native-iot-wifi`

**Comment by thehellmaker** [comment]
Thanks. But i have done this react-native link react-native-iot-wifi 

and also followed the ios sectiosn but i still see 

`error: bundling failed: Error: Unable to resolve module `react-native-iot-wifi` from `/Users/aashok/Documents/test/testapp/src/App.js`: Module `react-native-iot-wifi` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (/Users/aashok/Documents/test/testapp/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:183:15)
    at ResolutionRequest.resolveDependency (/Users/aashok/Documents/test/testapp/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/aashok/Documents/test/testapp/node_modules/metro/src/node-haste/DependencyGraph.js:283:16)
    at Object.resolve (/Users/aashok/Documents/test/testapp/node_modules/metro/src/lib/transformHelpers.js:261:42)
    at /Users/aashok/Documents/test/testapp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:399:31
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/aashok/Documents/test/testapp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:18)
    at /Users/aashok/Documents/test/testapp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:269:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/aashok/Documents/test/testapp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)`

**Comment by thehellmaker** [comment]
I deleted the node_modules folder and re ran npm install. It worked.

Here are the final steps and the documentation can be improved as follows
1. npm install --save react-native-iot-wifi
2. react-native link react-native-iot-wifi
3. And then mandatorily follow the ios Section  

iOS
Important IOTWifi uses NEHotspotConfigurationManager. To use the NEHotspotConfigurationManager class, you must enable the Hotspot Configuration capability in Xcode.

Drang an drop IOTWifi.xcodeproj to your workspace
Link target to libIOTWifi.a library
Link target to NetworkExtension.framework framework
Enable Hotspot Configuration
For iOS 12 Enable Access WiFi Information

4. Delete node_modules folder and npm install 
5. Run the app
