### ISSUE TITLE
Wifi.connect 

### ISSUE THREAD

**Issue by Chatharaju** [tadasr/react-native-iot-wifi#4]
Hi there,

Will Wifi.connect() and wifi.connectSecure() are not able to connect.

**Comment by tadasr** [comment]
Hi @Chatharaju,

Sorry for delay. I'm bit off this project. `Wifi.connect()` should work. On what platform it fails to connect? What device and os version are you using?
I do not think that `Wifi.connectSecure()` is implemented.

**Comment by tadasr** [comment]
Works with iOS 12 & Android 8.1.0.
