### ISSUE TITLE
Remove example from npm production package

### ISSUE THREAD

**Issue by nkovacic** [tadasr/react-native-iot-wifi#7]
Example is not needed in npm production package. Would be great if there was a .npmignore to exclude it.

**Comment by nkovacic** [comment]
Added a [pull reques](https://github.com/tadasr/react-native-iot-wifi/pull/8)

**Comment by tadasr** [comment]
@nkovacic good point! I prefer whitelisting files in [package](https://github.com/tadasr/react-native-iot-wifi/blob/master/package.json) `files:`. I do not have experience with npm packages.

**Comment by nkovacic** [comment]
.npmignore file is much easier if you have alot of files. You only need to exclude example folder, everything else is fine.

**Comment by tadasr** [comment]
For big packages it makes sense, but here we only have 2 folders with several files. 
I updated [package](https://github.com/tadasr/react-native-iot-wifi/commit/0aafe23fe08769f0ae505231a45990cc931a1439) file.
